// AUTH TYPES
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// ERROR TYPES
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// API TYPES
export const GET_USERS = "GET_USERS";
export const GET_OFFERS = "GET_OFFERS";
export const OFFERS_LOADING = "OFFERS_LOADING";
export const GET_OFFERS_ERROR = "GET_OFFERS_ERROR";
export const ADD_OFFER_SUCCESS = "ADD_OFFER_SUCCESS";
